### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jackding79** [jackding79/currentdemo#1]
```java
 static int i=0;
    public static void remove(File file){
        if(file.isDirectory()){
            File fs[]=file.listFiles();
            for(File f:fs){
                if(f.isFile()) {
                    if (f.getName().endsWith("_remote.repositories")) {
                        f.delete();
                        i++;
                        System.out.println("["+i+"]"+"delete： "+f.getAbsolutePath());
                    }
                }else{
                    remove(f);
                }
            }
        }
```
```yaml
feign:
  client:
    config:
      provider:
        connectTimeout: 1000
        readTimeout: 1000
```
